"""Add last_watered to Device

Revision ID: a16eed69b1dc
Revises: cb3ffa209e89
Create Date: 2025-07-21 03:48:56.828420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16eed69b1dc'
down_revision = 'cb3ffa209e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_watered', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('last_watered')

    # ### end Alembic commands ###
