"""rename raw_moisture

Revision ID: cb3ffa209e89
Revises: 
Create Date: 2025-07-19 18:55:43.936613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3ffa209e89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_moisture', sa.Float(), nullable=True))
        batch_op.drop_column('current_moisture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_moisture', sa.FLOAT(), nullable=True))
        batch_op.drop_column('raw_moisture')

    # ### end Alembic commands ###
